name: Deploy pages

on:
  push:
    branches: [main]
    paths:
      - docs/**/*

jobs:
  deploy_pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: cd docs && yarn install && yarn build

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: hdnum_docs.yml
          name: HDNUM_DOCS-artifact

      - name: "Untar files"
        run: |
          tar -I zstd -xvf HDNUM_DOCS.tar.zst
          OUTPUT_DIR=docs/src/.vuepress/dist/files
          mkdir -p $OUTPUT_DIR
          wget https://docs.paraview.org/_/downloads/en/latest/pdf/ -O $OUTPUT_DIR/docs-paraview-org-en-latest.pdf
          wget https://dumux.org/docs/handbook/master/dumux-handbook.pdf -O $OUTPUT_DIR/dumux-handbook.pdf
          wget --no-check-certificate https://elib.uni-stuttgart.de/bitstream/11682/9377/1/simtech-tr2017-1_coupling-dumux-and-pdelab-to-investigate-evaporation.pdf -O $OUTPUT_DIR/simtech-tr2017-1_coupling-dumux-and-pdelab-to-investigate-evaporation.pdf
          mv doc/html $OUTPUT_DIR/hdnum
          mv tutorial/hdnum.pdf $OUTPUT_DIR
          mv tutorial/hdnum-tutorial-article.pdf $OUTPUT_DIR
          mv tutorial/hdnum-tutorial-beamer.pdf $OUTPUT_DIR
          mv doc/latex/refman.pdf $OUTPUT_DIR
          mv programmierkurs/programmierkurs*.pdf $OUTPUT_DIR

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/src/.vuepress/dist
          force_orphan: true
          publish_branch: gh-pages
